#!/usr/bin/env python3
"""Convert Polished Crystal's 16x96 Chris walking sheet to Expansion's 144x32 layout.

This is intentionally dependency-free. It supports the exact RGBDS-style
2-bit grayscale PNG used by the pinned Polished Crystal v3.2.3 source.

Source frame order:
    0 south idle
    1 north idle
    2 west idle
    3 south step
    4 north step
    5 west step

Expansion target frame order:
    0 south idle
    1 north idle
    2 west idle
    3 south step A
    4 south step B (horizontal flip of source frame 3)
    5 north step A
    6 north step B (horizontal flip of source frame 4)
    7 west step A
    8 west step B (same source frame 5)

East is generated by Expansion's animation table with horizontal flip.
"""

from __future__ import annotations

import argparse
import binascii
import struct
import zlib
from pathlib import Path

PNG_SIG = b"\x89PNG\r\n\x1a\n"


def _paeth(a: int, b: int, c: int) -> int:
    p = a + b - c
    pa = abs(p - a)
    pb = abs(p - b)
    pc = abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    if pb <= pc:
        return b
    return c


def _read_png_2bit_grayscale(path: Path) -> tuple[int, int, list[list[int]]]:
    data = path.read_bytes()
    if not data.startswith(PNG_SIG):
        raise ValueError(f"{path}: not a PNG")

    pos = len(PNG_SIG)
    width = height = bit_depth = color_type = interlace = None
    idat = bytearray()

    while pos < len(data):
        length = struct.unpack(">I", data[pos:pos + 4])[0]
        kind = data[pos + 4:pos + 8]
        payload = data[pos + 8:pos + 8 + length]
        pos += 12 + length

        if kind == b"IHDR":
            width, height, bit_depth, color_type, comp, filt, interlace = struct.unpack(
                ">IIBBBBB", payload
            )
            if comp != 0 or filt != 0:
                raise ValueError("unsupported PNG compression/filter method")
        elif kind == b"IDAT":
            idat.extend(payload)
        elif kind == b"IEND":
            break

    if (bit_depth, color_type, interlace) != (2, 0, 0):
        raise ValueError(
            f"expected non-interlaced 2-bit grayscale PNG, got "
            f"bit_depth={bit_depth}, color_type={color_type}, interlace={interlace}"
        )

    packed_row_bytes = (width * 2 + 7) // 8
    raw = zlib.decompress(bytes(idat))
    expected = height * (1 + packed_row_bytes)
    if len(raw) != expected:
        raise ValueError(f"unexpected decompressed size {len(raw)} (expected {expected})")

    rows: list[bytes] = []
    prev = bytearray(packed_row_bytes)
    offset = 0

    for _ in range(height):
        filter_type = raw[offset]
        offset += 1
        scan = bytearray(raw[offset:offset + packed_row_bytes])
        offset += packed_row_bytes
        recon = bytearray(packed_row_bytes)

        for x, value in enumerate(scan):
            left = recon[x - 1] if x else 0
            up = prev[x]
            up_left = prev[x - 1] if x else 0

            if filter_type == 0:
                recon[x] = value
            elif filter_type == 1:
                recon[x] = (value + left) & 0xFF
            elif filter_type == 2:
                recon[x] = (value + up) & 0xFF
            elif filter_type == 3:
                recon[x] = (value + ((left + up) // 2)) & 0xFF
            elif filter_type == 4:
                recon[x] = (value + _paeth(left, up, up_left)) & 0xFF
            else:
                raise ValueError(f"unsupported PNG filter type {filter_type}")

        rows.append(bytes(recon))
        prev = recon

    pixels: list[list[int]] = []
    for packed in rows:
        row: list[int] = []
        for byte in packed:
            row.extend(((byte >> 6) & 3, (byte >> 4) & 3, (byte >> 2) & 3, byte & 3))
        pixels.append(row[:width])

    return width, height, pixels


def _chunk(kind: bytes, payload: bytes) -> bytes:
    crc = binascii.crc32(kind)
    crc = binascii.crc32(payload, crc) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + kind + payload + struct.pack(">I", crc)


def _write_indexed_4bit_png(path: Path, pixels: list[list[int]]) -> None:
    height = len(pixels)
    width = len(pixels[0]) if height else 0
    if width % 2:
        raise ValueError("4-bit output width must be even")

    # Index 0 is the GSC white/background color and is transparent for OBJ use.
    palette = bytes((
        255, 255, 255,
        170, 170, 170,
        85, 85, 85,
        0, 0, 0,
    ))
    transparency = bytes((0, 255, 255, 255))

    raw = bytearray()
    for row in pixels:
        raw.append(0)  # PNG filter: None
        for x in range(0, width, 2):
            raw.append(((row[x] & 0xF) << 4) | (row[x + 1] & 0xF))

    ihdr = struct.pack(">IIBBBBB", width, height, 4, 3, 0, 0, 0)
    out = (
        PNG_SIG
        + _chunk(b"IHDR", ihdr)
        + _chunk(b"PLTE", palette)
        + _chunk(b"tRNS", transparency)
        + _chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + _chunk(b"IEND", b"")
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(out)


def convert(source: Path, output: Path) -> None:
    width, height, src = _read_png_2bit_grayscale(source)
    if (width, height) != (16, 96):
        raise ValueError(f"expected 16x96 source, got {width}x{height}")

    frames = [src[i * 16:(i + 1) * 16] for i in range(6)]
    mapping = (
        (0, False),
        (1, False),
        (2, False),
        (3, False),
        (3, True),
        (4, False),
        (4, True),
        (5, False),
        (5, False),
    )

    # 9 frames x 16 px wide, each on a 16x32 GBA OBJ canvas.
    dst = [[0 for _ in range(144)] for _ in range(32)]

    # RGBDS grayscale convention is white=3, black=0. Re-index so white/background
    # becomes palette index 0 for the GBA OBJ transparency convention.
    remap = (3, 2, 1, 0)

    for target_index, (source_index, hflip) in enumerate(mapping):
        frame = frames[source_index]
        for y in range(16):
            source_row = frame[y]
            for x in range(16):
                sx = 15 - x if hflip else x
                dst[16 + y][target_index * 16 + x] = remap[source_row[sx]]

    _write_indexed_4bit_png(output, dst)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="Polished Crystal gfx/sprites/chris.png")
    parser.add_argument("output", type=Path, help="output polished_chris/walking.png")
    args = parser.parse_args()
    convert(args.source, args.output)


if __name__ == "__main__":
    main()
